services:
  chat-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: chat
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
